"""add_schedule_items_table

Revision ID: 0d97e0a2b8e0
Revises: 071cc8e0d14f
Create Date: 2026-06-05 10:57:20.546551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d97e0a2b8e0'
down_revision: Union[str, None] = '071cc8e0d14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
