"""Add message read state table

Revision ID: 456e60571725
Revises: 8171fd0e4ee6
Create Date: 2026-06-03 10:55:12.194318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456e60571725'
down_revision: Union[str, None] = '8171fd0e4ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_read_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='_user_course_read_uc')
    )
    op.create_index(op.f('ix_message_read_states_course_id'), 'message_read_states', ['course_id'], unique=False)
    op.create_index(op.f('ix_message_read_states_id'), 'message_read_states', ['id'], unique=False)
    op.create_index(op.f('ix_message_read_states_user_id'), 'message_read_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_read_states_user_id'), table_name='message_read_states')
    op.drop_index(op.f('ix_message_read_states_id'), table_name='message_read_states')
    op.drop_index(op.f('ix_message_read_states_course_id'), table_name='message_read_states')
    op.drop_table('message_read_states')
    # ### end Alembic commands ###
