"""Add expires_at to announcements

Revision ID: 8171fd0e4ee6
Revises: f7c5fc67cd17
Create Date: 2026-06-03 08:56:07.748966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8171fd0e4ee6'
down_revision: Union[str, None] = 'f7c5fc67cd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_announcements_expires_at'), 'announcements', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_expires_at'), table_name='announcements')
    op.drop_column('announcements', 'expires_at')
    # ### end Alembic commands ###
