"""Add chat reply and edit columns

Revision ID: 8bd9808a42e0
Revises: f4a3b5c6d7e8
Create Date: 2026-06-03 01:58:31.677723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd9808a42e0'
down_revision: Union[str, None] = 'f4a3b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###
