"""add_avatar_url_to_users_retry

Revision ID: 9e3fb597e429
Revises: a2d4e6f8b9c1
Create Date: 2026-06-04 21:54:27.344068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3fb597e429'
down_revision: Union[str, None] = 'a2d4e6f8b9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_course_read_uc', 'message_read_states', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_course_read_uc', 'message_read_states', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
