"""Update quiz models and add quizzes table

Revision ID: c424fefe49db
Revises: 8bd9808a42e0
Create Date: 2026-06-03 06:53:44.270522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c424fefe49db'
down_revision: Union[str, None] = '8bd9808a42e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum type manually for PostgreSQL
    question_type_enum = sa.Enum('MULTIPLE_CHOICE', 'FILL_IN_THE_BLANKS', 'OBJECTIVE', 'ESSAY', name='questiontype')
    question_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes_lesson_id'), 'quizzes', ['lesson_id'], unique=True)
    op.add_column('quiz_attempts', sa.Column('quiz_id', sa.UUID(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('total_points', sa.Integer(), nullable=True))
    op.drop_index('ix_quiz_attempts_lesson_id', table_name='quiz_attempts')
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.drop_constraint('quiz_attempts_lesson_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('quiz_attempts', 'lesson_id')
    op.drop_column('quiz_attempts', 'total')
    op.add_column('quiz_questions', sa.Column('quiz_id', sa.UUID(), nullable=False))
    op.add_column('quiz_questions', sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'FILL_IN_THE_BLANKS', 'OBJECTIVE', 'ESSAY', name='questiontype'), nullable=False))
    op.add_column('quiz_questions', sa.Column('question_data', sa.JSON(), nullable=False))
    op.add_column('quiz_questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.drop_index('ix_quiz_questions_lesson_id', table_name='quiz_questions')
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.drop_constraint('quiz_questions_lesson_id_fkey', 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('quiz_questions', 'lesson_id')
    op.drop_column('quiz_questions', 'options')
    op.drop_column('quiz_questions', 'correct_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('correct_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quiz_questions', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('quiz_questions', sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key('quiz_questions_lesson_id_fkey', 'quiz_questions', 'lessons', ['lesson_id'], ['id'])
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.create_index('ix_quiz_questions_lesson_id', 'quiz_questions', ['lesson_id'], unique=False)
    op.drop_column('quiz_questions', 'explanation')
    op.drop_column('quiz_questions', 'question_data')
    op.drop_column('quiz_questions', 'question_type')
    op.drop_column('quiz_questions', 'quiz_id')
    op.add_column('quiz_attempts', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quiz_attempts', sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key('quiz_attempts_lesson_id_fkey', 'quiz_attempts', 'lessons', ['lesson_id'], ['id'])
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.create_index('ix_quiz_attempts_lesson_id', 'quiz_attempts', ['lesson_id'], unique=False)
    op.drop_column('quiz_attempts', 'total_points')
    op.drop_column('quiz_attempts', 'quiz_id')
    op.drop_index(op.f('ix_quizzes_lesson_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_table('quizzes')
    
    # Drop the enum type manually
    question_type_enum = sa.Enum('MULTIPLE_CHOICE', 'FILL_IN_THE_BLANKS', 'OBJECTIVE', 'ESSAY', name='questiontype')
    question_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
