"""add_enrollment_status

Revision ID: da00fe30e737
Revises: 9e3fb597e429
Create Date: 2026-06-05 02:00:16.098730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da00fe30e737'
down_revision: Union[str, None] = '9e3fb597e429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually create the enum type first
    status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='enrollmentstatus')
    status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('enrollments', sa.Column('status', status_enum, nullable=False, server_default='PENDING'))
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_column('enrollments', 'status')
    
    # Manually drop the enum type
    sa.Enum(name='enrollmentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
