"""Add instructor feedback to quiz attempts

Revision ID: f7c5fc67cd17
Revises: c424fefe49db
Create Date: 2026-06-03 07:23:18.661944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c5fc67cd17'
down_revision: Union[str, None] = 'c424fefe49db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('instructor_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'instructor_feedback')
    # ### end Alembic commands ###
