"""add image_url to courses

Revision ID: f8f0c920d5a1
Revises: 456e60571725
Create Date: 2026-06-03 16:28:12.577127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f0c920d5a1'
down_revision: Union[str, None] = '456e60571725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'image_url')
    # ### end Alembic commands ###
